name: match
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  stroke_text: ^0.0.3
  pausable_timer: ^3.1.0+3
  audioplayers: ^6.1.2
  # audiofilereader: ^2.1.3
  dio: ^5.7.0
  # flutter_barcode_scanner: ^2.0.0
  flutter_colorpicker: ^1.1.0
  # qr_code_scanner: ^0.7.0
  mobile_scanner: ^6.0.6
  animated_float_action_button: ^1.0.4
  video_player: ^2.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/backgrounds/
   - assets/puzzles/
   - assets/puzzles/0/
   - assets/puzzles/1/
   - assets/puzzles/2/
   - assets/puzzles/3/
   - assets/puzzles/4/
   - assets/puzzles/5/
   - assets/puzzles/6/
   - assets/puzzles/7/
   - assets/puzzles/8/
   - assets/puzzles/9/
   - assets/icons/
   - assets/images/number/
   - assets/audio/
   - assets/videos/
  fonts:
    - family: Trace
      fonts:
        - asset: assets/fonts/Trace-lxy0.ttf
  #  - assets/audio/
