name: doudi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.2+9

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  stroke_text: ^0.0.3
  pausable_timer: ^3.1.0+3
  audioplayers: ^6.1.2
  # audiofilereader: ^2.1.3
  dio: ^5.7.0
  # flutter_barcode_scanner: ^2.0.0
  flutter_colorpicker: ^1.1.0
  # qr_code_scanner: ^0.7.0
  # mobile_scanner: ^6.0.6
  animated_float_action_button: ^1.0.4
  # video_player: ^2.7.1
  # scan: ^1.6.0
  # barcode_scan2: ^4.5.0
  # flutter_barcode_scanner: ^2.0.0
  simple_barcode_scanner: ^0.3.0
  mobile_device_identifier: ^0.0.3
  shared_preferences: ^2.5.2
  # native_video_player: ^2.0.0
  # flick_video_player: ^0.9.0
  # appinio_video_player: ^1.3.0
  pod_player: ^0.2.2
  screenshot: ^3.0.0
  path_provider: ^2.1.5
  # image_gallery_saver: '^2.0.3'
  share_plus: ^10.1.4
  # native_screenshot: ^1.0.0
  saver_gallery: ^4.0.0
  confetti: ^0.8.0
  youtube_player_flutter: ^9.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/backgrounds/
   - assets/puzzles/
   - assets/puzzles/0/
   - assets/puzzles/1/
   - assets/puzzles/2/
   - assets/puzzles/3/
   - assets/puzzles/4/
   - assets/puzzles/5/
   - assets/puzzles/6/
   - assets/puzzles/7/
   - assets/puzzles/8/
   - assets/puzzles/9/
   - assets/icons/
   - assets/images/number/
   - assets/audio/
   - assets/videos/
  fonts:
    - family: Trace
      fonts:
        - asset: assets/fonts/Trace-lxy0.ttf
  #  - assets/audio/
